s = set()

i = input("Enter a unique number: ")
s.add(int(i))
i = input("Enter a unique number: ")
s.add(int(i))
i = input("Enter a unique number: ")
s.add(int(i))
i = input("Enter a unique number: ")
s.add(int(i))
i = input("Enter a unique number: ")
s.add(int(i))
i = input("Enter a unique number: ")
s.add(int(i))
i = input("Enter a unique number: ")
s.add(int(i))
i = input("Enter a unique number: ")
s.add(int(i))
print(s)
